// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package greeter

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GreetRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGreetRequest(buf []byte, offset flatbuffers.UOffsetT) *GreetRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GreetRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsGreetRequest(buf []byte, offset flatbuffers.UOffsetT) *GreetRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GreetRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *GreetRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GreetRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GreetRequest) Greeting() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GreetRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GreetRequestAddGreeting(builder *flatbuffers.Builder, greeting flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(greeting), 0)
}
func GreetRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
