// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package greeter

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GreetResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsGreetResponse(buf []byte, offset flatbuffers.UOffsetT) *GreetResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GreetResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsGreetResponse(buf []byte, offset flatbuffers.UOffsetT) *GreetResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GreetResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *GreetResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GreetResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GreetResponse) Ack() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GreetResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GreetResponseAddAck(builder *flatbuffers.Builder, ack flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ack), 0)
}
func GreetResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
